-- 019_project_data_identity: Git-shareable project/conversation/attachment identities.
-- UUIDv7 values are backfilled and generated by migrate.ts after this additive schema migration.

ALTER TABLE projects ADD COLUMN sync_uid TEXT;
CREATE UNIQUE INDEX idx_projects_sync_uid ON projects(sync_uid) WHERE sync_uid IS NOT NULL;

ALTER TABLE conversations ADD COLUMN sync_uid TEXT;
CREATE UNIQUE INDEX idx_conversations_sync_uid ON conversations(sync_uid) WHERE sync_uid IS NOT NULL;

CREATE TABLE project_attachments (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  sync_uid   TEXT,
  path       TEXT NOT NULL,
  sha256     TEXT NOT NULL CHECK (length(sha256) = 64),
  mime_type  TEXT,
  size       INTEGER NOT NULL CHECK (size >= 0),
  created_ts INTEGER NOT NULL,
  UNIQUE(project_id, path)
);
CREATE UNIQUE INDEX idx_project_attachments_sync_uid
  ON project_attachments(sync_uid) WHERE sync_uid IS NOT NULL;
CREATE INDEX idx_project_attachments_project ON project_attachments(project_id, created_ts, id);
