import type { SupportedLocale } from '../locales';

const en = {
  'design.runQueued': 'Design run queued.', 'design.runMode': 'Collaboration mode',
  'design.mode.goal': 'Clarify goal', 'design.mode.solution': 'Shape solution', 'design.mode.review': 'Review design', 'design.mode.graph': 'Build graph',
  'design.run.queued': 'Queued', 'design.run.running': 'Running', 'design.run.completed': 'Completed', 'design.run.failed': 'Failed', 'design.run.cancelled': 'Cancelled',
  'design.message': 'Message to the design team', 'design.messagePlaceholder': 'Add a need, answer a question, or ask for a review…', 'design.sendShortcut': 'Command or Control + Enter', 'design.send': 'Send', 'design.sending': 'Sending…',
  'design.nextQuestion': 'Best next question', 'design.nextQuestionEmpty': 'No blocking question remains.',
  'design.dimension.goal_clarity': 'Goal clarity', 'design.dimension.scope_boundaries': 'Scope boundaries', 'design.dimension.solution_completeness': 'Solution completeness', 'design.dimension.dependencies_constraints': 'Dependencies and constraints', 'design.dimension.acceptance_testability': 'Acceptance testability', 'design.dimension.risks_unknowns': 'Risks and unknowns',
  'design.delivery': 'Delivery', 'design.worktree': 'Execution workspace', 'design.currentWorkspace': 'Current checkout', 'design.createWorktree': 'Create worktree', 'design.inspect': 'Inspect', 'design.execute': 'Start execution',
  'design.files': 'Design files', 'design.noChanges': 'No projected file changes.', 'design.overwrite': 'Overwrite reviewed conflicts',
  'design.granularity': 'Issue granularity', 'design.granularity.milestone': 'Milestones', 'design.granularity.module': 'Modules', 'design.granularity.balanced': 'Balanced', 'design.granularity.small': 'Small issues', 'design.granularity.atomic': 'Atomic issues',
  'design.publishIssues': 'Review issue draft', 'design.publishPreview': 'Confirm issue publication', 'design.publishPreviewHelp': 'This creates the listed issues as one atomic publication.', 'design.confirmPublish': 'Create issues',
  'design.workspaceChoice': 'Execution workspace', 'design.baseRef': 'Base branch reference',
  'design.syncPending': 'Sync needed', 'design.apply': 'Apply', 'design.ignore': 'Ignore', 'design.supplement': 'Create supplement', 'design.confirmDelivered': 'Confirm delivered', 'design.retrySync': 'Retry sync',
  'design.assetPrompt': 'Describe the page or visual to generate', 'design.generateAsset': 'Generate visual',
} as const;
type Keys = keyof typeof en;
type Catalog = Record<Keys, string>;

const zhHans: Catalog = {
  'design.runQueued':'设计任务已排队。','design.runMode':'协作模式','design.mode.goal':'澄清目标','design.mode.solution':'形成方案','design.mode.review':'评审设计','design.mode.graph':'生成任务图','design.run.queued':'排队中','design.run.running':'运行中','design.run.completed':'已完成','design.run.failed':'失败','design.run.cancelled':'已取消','design.message':'发给设计团队的消息','design.messagePlaceholder':'补充需求、回答问题或请求评审…','design.sendShortcut':'⌘/Ctrl + Enter','design.send':'发送','design.sending':'发送中…','design.nextQuestion':'最值得继续澄清的问题','design.nextQuestionEmpty':'当前没有阻塞问题。','design.dimension.goal_clarity':'目标清晰度','design.dimension.scope_boundaries':'范围边界','design.dimension.solution_completeness':'方案完整度','design.dimension.dependencies_constraints':'依赖与约束','design.dimension.acceptance_testability':'验收可测试性','design.dimension.risks_unknowns':'风险与未知项','design.delivery':'交付','design.worktree':'执行工作区','design.currentWorkspace':'当前检出目录','design.createWorktree':'创建 worktree','design.inspect':'检查','design.execute':'开始执行','design.files':'设计文件','design.noChanges':'没有待写入的设计文件变化。','design.overwrite':'覆盖已审查的冲突','design.granularity':'Issue 拆分力度','design.granularity.milestone':'里程碑','design.granularity.module':'模块','design.granularity.balanced':'均衡','design.granularity.small':'小 Issue','design.granularity.atomic':'原子 Issue','design.publishIssues':'审查 Issue 草案','design.publishPreview':'确认发布 Issue','design.publishPreviewHelp':'将以下 Issue 作为一个原子批次创建。','design.confirmPublish':'创建 Issue','design.workspaceChoice':'选择执行工作区','design.baseRef':'基础分支引用','design.syncPending':'需要同步','design.apply':'应用','design.ignore':'忽略','design.supplement':'创建补充 Issue','design.confirmDelivered':'确认已交付','design.retrySync':'重试同步','design.assetPrompt':'描述要生成的页面或视觉','design.generateAsset':'生成视觉',
};

const translations: Record<Exclude<SupportedLocale, 'en' | 'zh-Hans'>, Catalog> = {
  'zh-Hant': { ...zhHans, 'design.runQueued':'設計任務已排隊。','design.runMode':'協作模式','design.mode.goal':'釐清目標','design.mode.solution':'形成方案','design.mode.review':'審查設計','design.mode.graph':'產生任務圖','design.send':'傳送','design.sending':'傳送中…','design.nextQuestion':'下一個最重要的問題','design.nextQuestionEmpty':'目前沒有阻塞問題。','design.delivery':'交付','design.worktree':'執行工作區','design.currentWorkspace':'目前檢出目錄','design.createWorktree':'建立 worktree','design.inspect':'檢查','design.execute':'開始執行','design.files':'設計檔案','design.noChanges':'沒有待寫入的設計檔案變更。','design.granularity':'Issue 拆分粒度','design.publishIssues':'審查 Issue 草稿','design.publishPreview':'確認發佈 Issue','design.publishPreviewHelp':'以下 Issue 將以單一原子批次建立。','design.confirmPublish':'建立 Issue','design.syncPending':'需要同步','design.apply':'套用','design.ignore':'忽略','design.supplement':'建立補充 Issue','design.assetPrompt':'描述要產生的頁面或視覺','design.generateAsset':'產生視覺' },
  ja: { ...zhHans, 'design.runQueued':'デザイン実行をキューに追加しました。','design.runMode':'協働モード','design.mode.goal':'目標を明確化','design.mode.solution':'解決策を設計','design.mode.review':'設計をレビュー','design.mode.graph':'グラフを作成','design.run.queued':'待機中','design.run.running':'実行中','design.run.completed':'完了','design.run.failed':'失敗','design.run.cancelled':'キャンセル済み','design.message':'デザインチームへのメッセージ','design.messagePlaceholder':'要件の追加、質問への回答、レビューの依頼…','design.send':'送信','design.sending':'送信中…','design.nextQuestion':'次に確認すべき質問','design.nextQuestionEmpty':'未解決の質問はありません。','design.delivery':'デリバリー','design.worktree':'実行ワークスペース','design.currentWorkspace':'現在のチェックアウト','design.createWorktree':'worktree を作成','design.inspect':'確認','design.execute':'実行を開始','design.files':'設計ファイル','design.noChanges':'設計ファイルの変更はありません。','design.granularity':'Issue の粒度','design.publishIssues':'Issue 草案を確認','design.publishPreview':'Issue 公開の確認','design.publishPreviewHelp':'一覧の Issue を一つのアトミックな公開として作成します。','design.confirmPublish':'Issue を作成','design.syncPending':'同期が必要','design.apply':'適用','design.ignore':'無視','design.supplement':'補足 Issue を作成','design.assetPrompt':'生成するページやビジュアルを説明','design.generateAsset':'ビジュアルを生成' },
  ko: { ...zhHans, 'design.runQueued':'디자인 실행이 대기열에 추가되었습니다.','design.runMode':'협업 모드','design.mode.goal':'목표 명확화','design.mode.solution':'해결안 구성','design.mode.review':'디자인 검토','design.mode.graph':'그래프 작성','design.run.queued':'대기 중','design.run.running':'실행 중','design.run.completed':'완료','design.run.failed':'실패','design.run.cancelled':'취소됨','design.message':'디자인 팀에 보낼 메시지','design.messagePlaceholder':'요구사항 추가, 질문 답변 또는 검토 요청…','design.send':'보내기','design.sending':'보내는 중…','design.nextQuestion':'다음 핵심 질문','design.nextQuestionEmpty':'남은 차단 질문이 없습니다.','design.delivery':'전달','design.worktree':'실행 작업 공간','design.currentWorkspace':'현재 체크아웃','design.createWorktree':'worktree 만들기','design.inspect':'검사','design.execute':'실행 시작','design.files':'디자인 파일','design.noChanges':'예정된 파일 변경이 없습니다.','design.granularity':'Issue 세분화','design.publishIssues':'Issue 초안 검토','design.publishPreview':'Issue 게시 확인','design.publishPreviewHelp':'나열된 Issue를 하나의 원자적 게시로 생성합니다.','design.confirmPublish':'Issue 만들기','design.syncPending':'동기화 필요','design.apply':'적용','design.ignore':'무시','design.supplement':'보충 Issue 만들기','design.assetPrompt':'생성할 페이지 또는 비주얼 설명','design.generateAsset':'비주얼 생성' },
  es: { ...en, 'design.sendShortcut':'⌘ o Ctrl + Intro','design.dimension.goal_clarity':'Claridad del objetivo','design.dimension.scope_boundaries':'Límites del alcance','design.dimension.solution_completeness':'Integridad de la solución','design.dimension.dependencies_constraints':'Dependencias y restricciones','design.dimension.acceptance_testability':'Pruebas de aceptación','design.dimension.risks_unknowns':'Riesgos e incógnitas','design.granularity.milestone':'Hitos','design.granularity.module':'Módulos','design.granularity.balanced':'Equilibrada','design.granularity.small':'Issues pequeñas','design.granularity.atomic':'Issues atómicas','design.overwrite':'Sobrescribir conflictos revisados', 'design.runQueued':'La ejecución de diseño está en cola.','design.runMode':'Modo de colaboración','design.mode.goal':'Aclarar objetivo','design.mode.solution':'Definir solución','design.mode.review':'Revisar diseño','design.mode.graph':'Crear grafo','design.run.queued':'En cola','design.run.running':'En curso','design.run.completed':'Completada','design.run.failed':'Fallida','design.run.cancelled':'Cancelada','design.message':'Mensaje al equipo de diseño','design.messagePlaceholder':'Añade una necesidad, responde o solicita una revisión…','design.send':'Enviar','design.sending':'Enviando…','design.nextQuestion':'Mejor pregunta siguiente','design.nextQuestionEmpty':'No quedan preguntas bloqueantes.','design.delivery':'Entrega','design.worktree':'Espacio de ejecución','design.currentWorkspace':'Checkout actual','design.createWorktree':'Crear worktree','design.inspect':'Inspeccionar','design.execute':'Iniciar ejecución','design.files':'Archivos de diseño','design.noChanges':'No hay cambios proyectados.','design.granularity':'Granularidad de issues','design.publishIssues':'Revisar borrador','design.publishPreview':'Confirmar publicación','design.publishPreviewHelp':'Crea los issues listados como una publicación atómica.','design.confirmPublish':'Crear issues','design.syncPending':'Requiere sincronización','design.apply':'Aplicar','design.ignore':'Ignorar','design.supplement':'Crear complemento','design.assetPrompt':'Describe la página o visual','design.generateAsset':'Generar visual' },
  fr: { ...en, 'design.sendShortcut':'⌘ ou Ctrl + Entrée','design.dimension.goal_clarity':'Clarté de l’objectif','design.dimension.scope_boundaries':'Limites du périmètre','design.dimension.solution_completeness':'Complétude de la solution','design.dimension.dependencies_constraints':'Dépendances et contraintes','design.dimension.acceptance_testability':'Testabilité de l’acceptation','design.dimension.risks_unknowns':'Risques et inconnues','design.granularity.milestone':'Jalons','design.granularity.module':'Modules fonctionnels','design.granularity.balanced':'Équilibrée','design.granularity.small':'Petites issues','design.granularity.atomic':'Issues atomiques','design.overwrite':'Écraser les conflits examinés', 'design.runQueued':'L’exécution de conception est en attente.','design.runMode':'Mode de collaboration','design.mode.goal':'Clarifier l’objectif','design.mode.solution':'Définir la solution','design.mode.review':'Revoir la conception','design.mode.graph':'Créer le graphe','design.run.queued':'En attente','design.run.running':'En cours','design.run.completed':'Terminée','design.run.failed':'Échec','design.run.cancelled':'Annulée','design.message':'Message à l’équipe de conception','design.messagePlaceholder':'Ajoutez un besoin, répondez ou demandez une revue…','design.send':'Envoyer','design.sending':'Envoi…','design.nextQuestion':'Meilleure question suivante','design.nextQuestionEmpty':'Aucune question bloquante.','design.delivery':'Livraison','design.worktree':'Espace d’exécution','design.currentWorkspace':'Checkout actuel','design.createWorktree':'Créer le worktree','design.inspect':'Inspecter','design.execute':'Démarrer','design.files':'Fichiers de conception','design.noChanges':'Aucun changement de fichier prévu.','design.granularity':'Granularité des issues','design.publishIssues':'Revoir le brouillon','design.publishPreview':'Confirmer la publication','design.publishPreviewHelp':'Crée les issues listées dans une publication atomique.','design.confirmPublish':'Créer les issues','design.syncPending':'Synchronisation requise','design.apply':'Appliquer','design.ignore':'Ignorer','design.supplement':'Créer un complément','design.assetPrompt':'Décrivez la page ou le visuel','design.generateAsset':'Générer le visuel' },
  de: { ...en, 'design.sendShortcut':'⌘ oder Strg + Eingabe','design.dimension.goal_clarity':'Zielklarheit','design.dimension.scope_boundaries':'Umfangsgrenzen','design.dimension.solution_completeness':'Lösungsvollständigkeit','design.dimension.dependencies_constraints':'Abhängigkeiten und Einschränkungen','design.dimension.acceptance_testability':'Testbarkeit der Abnahme','design.dimension.risks_unknowns':'Risiken und Unbekannte','design.granularity.milestone':'Meilensteine','design.granularity.module':'Module','design.granularity.balanced':'Ausgewogen','design.granularity.small':'Kleine Issues','design.granularity.atomic':'Atomare Issues','design.overwrite':'Geprüfte Konflikte überschreiben', 'design.runQueued':'Designlauf wurde eingereiht.','design.runMode':'Zusammenarbeitsmodus','design.mode.goal':'Ziel klären','design.mode.solution':'Lösung ausarbeiten','design.mode.review':'Design prüfen','design.mode.graph':'Graph erstellen','design.run.queued':'Eingereiht','design.run.running':'Läuft','design.run.completed':'Abgeschlossen','design.run.failed':'Fehlgeschlagen','design.run.cancelled':'Abgebrochen','design.message':'Nachricht an das Designteam','design.messagePlaceholder':'Bedarf ergänzen, Frage beantworten oder Prüfung anfordern…','design.send':'Senden','design.sending':'Wird gesendet…','design.nextQuestion':'Beste nächste Frage','design.nextQuestionEmpty':'Keine blockierende Frage offen.','design.delivery':'Übergabe','design.worktree':'Ausführungsarbeitsbereich','design.currentWorkspace':'Aktueller Checkout','design.createWorktree':'Worktree erstellen','design.inspect':'Prüfen','design.execute':'Ausführung starten','design.files':'Designdateien','design.noChanges':'Keine vorgesehenen Dateiänderungen.','design.granularity':'Issue-Granularität','design.publishIssues':'Issue-Entwurf prüfen','design.publishPreview':'Veröffentlichung bestätigen','design.publishPreviewHelp':'Erstellt die Issues als eine atomare Veröffentlichung.','design.confirmPublish':'Issues erstellen','design.syncPending':'Synchronisierung nötig','design.apply':'Anwenden','design.ignore':'Ignorieren','design.supplement':'Ergänzung erstellen','design.assetPrompt':'Zu erzeugende Seite oder Grafik beschreiben','design.generateAsset':'Grafik erzeugen' },
  'pt-BR': { ...en, 'design.sendShortcut':'⌘ ou Ctrl + Enter','design.dimension.goal_clarity':'Clareza do objetivo','design.dimension.scope_boundaries':'Limites do escopo','design.dimension.solution_completeness':'Completude da solução','design.dimension.dependencies_constraints':'Dependências e restrições','design.dimension.acceptance_testability':'Testabilidade da aceitação','design.dimension.risks_unknowns':'Riscos e incógnitas','design.granularity.milestone':'Marcos','design.granularity.module':'Módulos','design.granularity.balanced':'Equilibrada','design.granularity.small':'Issues pequenas','design.granularity.atomic':'Issues atômicas','design.overwrite':'Sobrescrever conflitos revisados', 'design.runQueued':'A execução de design entrou na fila.','design.runMode':'Modo de colaboração','design.mode.goal':'Esclarecer objetivo','design.mode.solution':'Definir solução','design.mode.review':'Revisar design','design.mode.graph':'Criar grafo','design.run.queued':'Na fila','design.run.running':'Em execução','design.run.completed':'Concluída','design.run.failed':'Falhou','design.run.cancelled':'Cancelada','design.message':'Mensagem para a equipe de design','design.messagePlaceholder':'Adicione uma necessidade, responda ou peça uma revisão…','design.send':'Enviar','design.sending':'Enviando…','design.nextQuestion':'Melhor próxima pergunta','design.nextQuestionEmpty':'Não há perguntas bloqueadoras.','design.delivery':'Entrega','design.worktree':'Espaço de execução','design.currentWorkspace':'Checkout atual','design.createWorktree':'Criar worktree','design.inspect':'Inspecionar','design.execute':'Iniciar execução','design.files':'Arquivos de design','design.noChanges':'Não há mudanças de arquivo previstas.','design.granularity':'Granularidade de issues','design.publishIssues':'Revisar rascunho','design.publishPreview':'Confirmar publicação','design.publishPreviewHelp':'Cria as issues listadas como uma publicação atômica.','design.confirmPublish':'Criar issues','design.syncPending':'Sincronização necessária','design.apply':'Aplicar','design.ignore':'Ignorar','design.supplement':'Criar complemento','design.assetPrompt':'Descreva a página ou visual','design.generateAsset':'Gerar visual' },
  ru: { ...en, 'design.sendShortcut':'⌘ или Ctrl + Enter','design.dimension.goal_clarity':'Ясность цели','design.dimension.scope_boundaries':'Границы объёма','design.dimension.solution_completeness':'Полнота решения','design.dimension.dependencies_constraints':'Зависимости и ограничения','design.dimension.acceptance_testability':'Проверяемость приёмки','design.dimension.risks_unknowns':'Риски и неизвестные','design.granularity.milestone':'Этапы','design.granularity.module':'Модули','design.granularity.balanced':'Сбалансированно','design.granularity.small':'Малые задачи','design.granularity.atomic':'Атомарные задачи','design.overwrite':'Перезаписать проверенные конфликты', 'design.runQueued':'Запуск дизайна поставлен в очередь.','design.runMode':'Режим совместной работы','design.mode.goal':'Уточнить цель','design.mode.solution':'Сформировать решение','design.mode.review':'Проверить дизайн','design.mode.graph':'Создать граф','design.run.queued':'В очереди','design.run.running':'Выполняется','design.run.completed':'Завершено','design.run.failed':'Ошибка','design.run.cancelled':'Отменено','design.message':'Сообщение команде дизайна','design.messagePlaceholder':'Добавьте требование, ответьте или запросите проверку…','design.send':'Отправить','design.sending':'Отправка…','design.nextQuestion':'Лучший следующий вопрос','design.nextQuestionEmpty':'Блокирующих вопросов нет.','design.delivery':'Передача','design.worktree':'Рабочая область выполнения','design.currentWorkspace':'Текущий checkout','design.createWorktree':'Создать worktree','design.inspect':'Проверить','design.execute':'Начать выполнение','design.files':'Файлы дизайна','design.noChanges':'Изменений файлов нет.','design.granularity':'Детализация задач','design.publishIssues':'Проверить черновик','design.publishPreview':'Подтвердить публикацию','design.publishPreviewHelp':'Создаёт перечисленные задачи одной атомарной публикацией.','design.confirmPublish':'Создать задачи','design.syncPending':'Нужна синхронизация','design.apply':'Применить','design.ignore':'Игнорировать','design.supplement':'Создать дополнение','design.assetPrompt':'Опишите страницу или визуал','design.generateAsset':'Создать визуал' },
};

const workflowLabels: Record<Exclude<SupportedLocale, 'en' | 'zh-Hans'>, Pick<Catalog,
  'design.workspaceChoice' | 'design.baseRef' | 'design.confirmDelivered' | 'design.retrySync'>> = {
  'zh-Hant': { 'design.workspaceChoice':'選擇執行工作區', 'design.baseRef':'基礎分支參照', 'design.confirmDelivered':'確認已交付', 'design.retrySync':'重試同步' },
  ja: { 'design.workspaceChoice':'実行ワークスペースを選択', 'design.baseRef':'ベースブランチ参照', 'design.confirmDelivered':'配信済みを確認', 'design.retrySync':'同期を再試行' },
  ko: { 'design.workspaceChoice':'실행 작업 공간 선택', 'design.baseRef':'기준 브랜치 참조', 'design.confirmDelivered':'전달 완료 확인', 'design.retrySync':'동기화 재시도' },
  es: { 'design.workspaceChoice':'Elegir espacio de ejecución', 'design.baseRef':'Referencia de rama base', 'design.confirmDelivered':'Confirmar entrega', 'design.retrySync':'Reintentar sincronización' },
  fr: { 'design.workspaceChoice':'Choisir l’espace d’exécution', 'design.baseRef':'Référence de branche de base', 'design.confirmDelivered':'Confirmer la livraison', 'design.retrySync':'Relancer la synchronisation' },
  de: { 'design.workspaceChoice':'Ausführungsbereich wählen', 'design.baseRef':'Basis-Branch-Referenz', 'design.confirmDelivered':'Zustellung bestätigen', 'design.retrySync':'Synchronisierung wiederholen' },
  'pt-BR': { 'design.workspaceChoice':'Escolher espaço de execução', 'design.baseRef':'Referência do branch base', 'design.confirmDelivered':'Confirmar entrega', 'design.retrySync':'Tentar sincronização novamente' },
  ru: { 'design.workspaceChoice':'Выбрать рабочую область', 'design.baseRef':'Ссылка на базовую ветку', 'design.confirmDelivered':'Подтвердить доставку', 'design.retrySync':'Повторить синхронизацию' },
};

export const designWorkbenchAdvancedMessages: Readonly<Record<SupportedLocale, Catalog>> = {
  en,
  'zh-Hans': zhHans,
  'zh-Hant': { ...translations['zh-Hant'], ...workflowLabels['zh-Hant'] },
  ja: { ...translations.ja, ...workflowLabels.ja },
  ko: { ...translations.ko, ...workflowLabels.ko },
  es: { ...translations.es, ...workflowLabels.es },
  fr: { ...translations.fr, ...workflowLabels.fr },
  de: { ...translations.de, ...workflowLabels.de },
  'pt-BR': { ...translations['pt-BR'], ...workflowLabels['pt-BR'] },
  ru: { ...translations.ru, ...workflowLabels.ru },
};
