import type { SupportedLocale } from '../locales';

const en = {
  'errors.auth.invalid_credentials': 'The username or token is incorrect.',
  'errors.auth.required': 'Sign in to continue.',
  'errors.auth.admin_required': 'Administrator access is required.',
  'errors.auth.forbidden': 'You do not have permission to do this.',
  'errors.auth.route_undeclared': 'This route is unavailable.',
  'errors.project.required': 'A project ID is required.',
  'errors.project.not_found': 'The project does not exist.',
  'errors.legacy.error': 'The request could not be completed.',
  'errors.network.unreachable': 'Could not reach the server. Check your connection and try again.',
  'errors.http.unexpected_response': 'The server returned an unexpected response.',
} as const;

type Messages = { [K in keyof typeof en]: string };

export const errorMessages = {
  en,
  'zh-Hans': { 'errors.auth.invalid_credentials':'用户名或 Token 不正确。','errors.auth.required':'请先登录。','errors.auth.admin_required':'需要管理员权限。','errors.auth.forbidden':'你没有执行此操作的权限。','errors.auth.route_undeclared':'此路由暂不可用。','errors.project.required':'缺少项目 ID。','errors.project.not_found':'项目不存在。','errors.legacy.error':'请求未能完成。','errors.network.unreachable':'无法连接服务器，请检查网络后重试。','errors.http.unexpected_response':'服务器返回了无法识别的响应。' },
  'zh-Hant': { 'errors.auth.invalid_credentials':'使用者名稱或 Token 不正確。','errors.auth.required':'請先登入。','errors.auth.admin_required':'需要管理員權限。','errors.auth.forbidden':'你沒有執行此操作的權限。','errors.auth.route_undeclared':'此路由目前無法使用。','errors.project.required':'缺少專案 ID。','errors.project.not_found':'專案不存在。','errors.legacy.error':'要求未能完成。','errors.network.unreachable':'無法連線至伺服器，請檢查網路後重試。','errors.http.unexpected_response':'伺服器傳回了無法識別的回應。' },
  ja: { 'errors.auth.invalid_credentials':'ユーザー名またはトークンが正しくありません。','errors.auth.required':'続行するにはログインしてください。','errors.auth.admin_required':'管理者権限が必要です。','errors.auth.forbidden':'この操作を行う権限がありません。','errors.auth.route_undeclared':'このルートは利用できません。','errors.project.required':'プロジェクト ID が必要です。','errors.project.not_found':'プロジェクトが存在しません。','errors.legacy.error':'リクエストを完了できませんでした。','errors.network.unreachable':'サーバーに接続できません。ネットワークを確認して再試行してください。','errors.http.unexpected_response':'サーバーから予期しない応答が返されました。' },
  ko: { 'errors.auth.invalid_credentials':'사용자 이름 또는 토큰이 올바르지 않습니다.','errors.auth.required':'계속하려면 로그인하세요.','errors.auth.admin_required':'관리자 권한이 필요합니다.','errors.auth.forbidden':'이 작업을 수행할 권한이 없습니다.','errors.auth.route_undeclared':'이 경로를 사용할 수 없습니다.','errors.project.required':'프로젝트 ID가 필요합니다.','errors.project.not_found':'프로젝트가 존재하지 않습니다.','errors.legacy.error':'요청을 완료하지 못했습니다.','errors.network.unreachable':'서버에 연결할 수 없습니다. 네트워크를 확인하고 다시 시도하세요.','errors.http.unexpected_response':'서버가 예상하지 못한 응답을 반환했습니다.' },
  es: { 'errors.auth.invalid_credentials':'El nombre de usuario o el token son incorrectos.','errors.auth.required':'Inicia sesión para continuar.','errors.auth.admin_required':'Se requiere acceso de administrador.','errors.auth.forbidden':'No tienes permiso para hacer esto.','errors.auth.route_undeclared':'Esta ruta no está disponible.','errors.project.required':'Se requiere un ID de proyecto.','errors.project.not_found':'El proyecto no existe.','errors.legacy.error':'No se pudo completar la solicitud.','errors.network.unreachable':'No se pudo conectar con el servidor. Comprueba tu conexión e inténtalo de nuevo.','errors.http.unexpected_response':'El servidor devolvió una respuesta inesperada.' },
  fr: { 'errors.auth.invalid_credentials':'Le nom d’utilisateur ou le jeton est incorrect.','errors.auth.required':'Connectez-vous pour continuer.','errors.auth.admin_required':'Un accès administrateur est requis.','errors.auth.forbidden':'Vous n’avez pas l’autorisation d’effectuer cette action.','errors.auth.route_undeclared':'Cette route est indisponible.','errors.project.required':'Un identifiant de projet est requis.','errors.project.not_found':'Le projet n’existe pas.','errors.legacy.error':'La requête n’a pas pu être effectuée.','errors.network.unreachable':'Impossible de joindre le serveur. Vérifiez votre connexion et réessayez.','errors.http.unexpected_response':'Le serveur a renvoyé une réponse inattendue.' },
  de: { 'errors.auth.invalid_credentials':'Benutzername oder Token ist falsch.','errors.auth.required':'Melden Sie sich an, um fortzufahren.','errors.auth.admin_required':'Administratorzugriff ist erforderlich.','errors.auth.forbidden':'Sie sind zu dieser Aktion nicht berechtigt.','errors.auth.route_undeclared':'Diese Route ist nicht verfügbar.','errors.project.required':'Eine Projekt-ID ist erforderlich.','errors.project.not_found':'Das Projekt existiert nicht.','errors.legacy.error':'Die Anfrage konnte nicht abgeschlossen werden.','errors.network.unreachable':'Der Server ist nicht erreichbar. Prüfen Sie die Verbindung und versuchen Sie es erneut.','errors.http.unexpected_response':'Der Server hat eine unerwartete Antwort zurückgegeben.' },
  'pt-BR': { 'errors.auth.invalid_credentials':'O nome de usuário ou o token está incorreto.','errors.auth.required':'Entre para continuar.','errors.auth.admin_required':'É necessário acesso de administrador.','errors.auth.forbidden':'Você não tem permissão para fazer isso.','errors.auth.route_undeclared':'Esta rota não está disponível.','errors.project.required':'É necessário informar o ID do projeto.','errors.project.not_found':'O projeto não existe.','errors.legacy.error':'Não foi possível concluir a solicitação.','errors.network.unreachable':'Não foi possível acessar o servidor. Verifique a conexão e tente novamente.','errors.http.unexpected_response':'O servidor retornou uma resposta inesperada.' },
  ru: { 'errors.auth.invalid_credentials':'Неверное имя пользователя или токен.','errors.auth.required':'Войдите, чтобы продолжить.','errors.auth.admin_required':'Требуются права администратора.','errors.auth.forbidden':'У вас нет прав на это действие.','errors.auth.route_undeclared':'Этот маршрут недоступен.','errors.project.required':'Требуется идентификатор проекта.','errors.project.not_found':'Проект не существует.','errors.legacy.error':'Не удалось выполнить запрос.','errors.network.unreachable':'Не удалось подключиться к серверу. Проверьте соединение и повторите попытку.','errors.http.unexpected_response':'Сервер вернул неожиданный ответ.' },
} as const satisfies Record<SupportedLocale, Messages>;
