import type { SupportedLocale } from '../locales';

const en = {
  'notify.statusChange':'🔄 [issue #{id}] {summary}',
  'notify.done':'✅ [issue #{id}] Done: {summary}',
  'notify.blocked':'⛔ [issue #{id}] Blocked: {summary}',
  // #275 / B-07：CLI 弹窗在等人选，issue 并没有进 blocked。用受阻文案会让人以为出事了
  'notify.choiceWaiting':'🔢 [issue #{id}] Needs your choice: {summary}',
  'notify.notExplained':'Not specified',
  'notify.gateWaiting':'Gate awaiting confirmation',
  'notify.waitingReply':'💬 **Waiting for your reply** — respond here or open the web app',
  'notify.selectionTitle':'🔢 {title} needs your choice',
  'notify.planEmpty':'(The plan is empty. Open the web app for details.)',
  'notify.planMore':'… ({count} steps total; see the rest in the web app)',
  'notify.planHeading':'**Plan ({count} steps · {mode})**',
  'notify.modeTeam':'team (single delivery)','notify.modeSeq':'sequential',
  'notify.branch':'Branch','notify.diffFailed':'⚠️ Could not generate the diff: {error}',
  'notify.diffTruncated':'(The diff was truncated.)','notify.fullDiffWeb':'Open the web app to review the full diff.',
  'notify.planGateTitle':'🚦 Plan awaiting confirmation · issue #{id}',
  'notify.mergeGateTitle':'🔍 Pre-merge review · issue #{id}',
  'notify.approve':'✅ Approve','notify.reject':'❌ Reject',
  'notify.oneTimeFooter':'Buttons work once; add detailed rejection feedback in the web app.',
  'notify.bindTest':'✅ PandaDOS connection test: this message confirms that notifications can reach you.',
  'notify.rejectNote':'Rejected from the Feishu card; add detailed feedback in the web app.',
  'notify.invalidCard':'Invalid card callback','notify.cardExpired':'This card has expired','notify.cardHandled':'This card was already handled','notify.cardNotYours':'This card was not sent to you','notify.gateUnavailable':'Gate handling is unavailable; use the web app','notify.failed':'Could not complete the action','notify.approved':'✅ Approved','notify.rejected':'❌ Rejected; add detailed feedback in the web app','notify.invalidSelection':'Invalid selection callback','notify.selectedOption':'Selected option {index}',
  'notify.summary.statusTransition':'{title}: {from} → {to}',
  'notify.summary.issueBlocked':'{title}: {detail}',
  'notify.summary.planReview':'Plan awaiting confirmation: {title}',
  'notify.summary.autoGitFailure':'{title}: automatic {action} failed (completion is unaffected): {detail}',
  'notify.summary.mergeReview':'Changes awaiting review: {title}',
  'notify.summary.conversationDisplaced':'{title}: execution paused because another project conversation is active. Switch back to this issue to resume automatically.',
  'notify.summary.menuStuck':'The CLI prompt has been waiting for {minutes} minutes and needs your input: {context}',
  'notify.summary.rateLimited':'{title}: usage limit reached; execution will resume automatically in {minutes} minutes.',
  'notify.summary.clarification':'“{title}” needs clarification during execution:\nRequirement: {body}\n{questions}\n(Open the issue to answer. Without a reply, execution continues with best judgment in {minutes} minutes.)',
  'notify.summary.clarificationNoBody':'“{title}” needs clarification during execution:\n{questions}\n(Open the issue to answer. Without a reply, execution continues with best judgment in {minutes} minutes.)',
  'notify.summary.seeConversation':'(See the conversation for details.)',
  'notify.summary.moduleOrganization':'Module organization analysis is complete: {total} suggestions ({merges} merges / {renames} renames / {creates} new modules / {moves} issue moves).\nOpen the Modules panel on the project page to review each action.',
  'notify.summary.analysisClarification':'“{title}” needs clarification after analysis:\nRequirement: {body}\n{questions}\n(A reply is optional; any reply will be added to the requirement.)',
  'notify.summary.analysisClarificationNoBody':'“{title}” needs clarification after analysis:\n{questions}\n(A reply is optional; any reply will be added to the requirement.)',
  'notify.summary.progress':'{emoji} {headline}',
  'notify.summary.progressNeedsReply':'{emoji} {headline} (Waiting for your reply)',
  'notify.summary.approvalSelection':'🔢 Input required: {context} (Open the web app to continue.)',
  // #273：nudge / judge 的自动重试到顶转人工。issue **不 block**，所以文案必须说清「还在跑」，
  // 否则用户会以为任务已经死了。reason 用 select 而不是拆两个 key，省去两套十语言翻译。
  // #274 止损闸：花销触顶主动停下。文案必须把「不是失败、也没取消」讲清楚，
  // 否则用户看到 issue 停了会以为任务挂了。数量按 metric 式写法（`blocks: 3`），
  // 任何数值下语法都成立，省掉三个数量参数各自的复数分支。
  'notify.summary.stopLossPaused':'{title}: paused by the cost guard ({reason, select, blocked {blocks: {blocks}} stage_reentry {stage re-entries: {reentries}} other {run time: {hours}h}}). Nothing failed and it was not cancelled — confirm to continue from the stage it stopped at.',
  'notify.summary.autoRetryExhausted':'{title}: {reason, select, nudge {automatic nudges} judge {completion checks} other {automatic retries}} stopped after {count, plural, one {# attempt} other {# attempts}} without progress. The issue is still running and was not blocked — take a look when you can.',
  // #279：批次全量回归守护。它不是某条 issue 的失败，也没建 issue——文案必须把这两点说清，
  // 否则用户会以为有任务挂了。退出码用 metric 式写法，任何数值下语法都成立。
  'notify.summary.regressionFailed':'{project}: the scheduled full regression failed at "{label}" (exit code: {code}). No issue was created and nothing is blocked — take a look when you can.',
  // #280：创建时澄清成功率跌破阈值。数量用 metric 式写法（`3/10`），避免十种语言各写一套复数分支。
  'notify.summary.clarifySuccessLow':'{project}: creation-time clarification is mostly failing ({ok}/{total} of the latest analyses succeeded). Each failed run still pays for a full repository read — check the clarify error events.',
} as const;

type Messages = { [K in keyof typeof en]: string };
const locale = (values: Partial<Messages>): Messages => ({ ...en, ...values });

const summaryTranslations: Record<Exclude<SupportedLocale, 'en'>, Partial<Messages>> = {
  'zh-Hans': {
    'notify.summary.statusTransition':'{title}：{from} → {to}','notify.summary.issueBlocked':'{title}：{detail}','notify.summary.planReview':'计划待确认：{title}','notify.summary.autoGitFailure':'{title}：自动 {action} 失败（不影响完成）：{detail}','notify.summary.mergeReview':'改动待审查：{title}','notify.summary.conversationDisplaced':'{title}：执行已暂停，因为项目当前使用的是其他对话。切回此 issue 后将自动继续。','notify.summary.menuStuck':'CLI 提示已等待 {minutes} 分钟，需要你处理：{context}','notify.summary.rateLimited':'{title}：已达到用量限制，将在 {minutes} 分钟后自动继续。','notify.summary.clarification':'“{title}”执行中需要你澄清：\n需求：{body}\n{questions}\n（请打开 issue 回答；若未回复，将在 {minutes} 分钟后按最佳判断继续。）','notify.summary.clarificationNoBody':'“{title}”执行中需要你澄清：\n{questions}\n（请打开 issue 回答；若未回复，将在 {minutes} 分钟后按最佳判断继续。）','notify.summary.seeConversation':'（详见对话。）',
  },
  'zh-Hant': {
    'notify.summary.statusTransition':'{title}：{from} → {to}','notify.summary.issueBlocked':'{title}：{detail}','notify.summary.planReview':'計畫待確認：{title}','notify.summary.autoGitFailure':'{title}：自動 {action} 失敗（不影響完成）：{detail}','notify.summary.mergeReview':'變更待審查：{title}','notify.summary.conversationDisplaced':'{title}：執行已暫停，因為專案目前使用其他對話。切回此 issue 後將自動繼續。','notify.summary.menuStuck':'CLI 提示已等待 {minutes} 分鐘，需要你處理：{context}','notify.summary.rateLimited':'{title}：已達用量限制，將在 {minutes} 分鐘後自動繼續。','notify.summary.clarification':'「{title}」執行中需要你釐清：\n需求：{body}\n{questions}\n（請開啟 issue 回答；若未回覆，將在 {minutes} 分鐘後依最佳判斷繼續。）','notify.summary.clarificationNoBody':'「{title}」執行中需要你釐清：\n{questions}\n（請開啟 issue 回答；若未回覆，將在 {minutes} 分鐘後依最佳判斷繼續。）','notify.summary.seeConversation':'（詳見對話。）',
  },
  ja: {
    'notify.summary.statusTransition':'{title}：{from} → {to}','notify.summary.issueBlocked':'{title}：{detail}','notify.summary.planReview':'計画の確認待ち：{title}','notify.summary.autoGitFailure':'{title}：自動 {action} に失敗しました（完了には影響しません）：{detail}','notify.summary.mergeReview':'変更のレビュー待ち：{title}','notify.summary.conversationDisplaced':'{title}：プロジェクトで別の会話が使用されているため、実行を一時停止しました。この issue に戻ると自動的に再開します。','notify.summary.menuStuck':'CLI のプロンプトが {minutes} 分間待機しています。入力してください：{context}','notify.summary.rateLimited':'{title}：利用上限に達しました。{minutes} 分後に自動的に再開します。','notify.summary.clarification':'「{title}」の実行に確認が必要です：\n要件：{body}\n{questions}\n（issue を開いて回答してください。回答がない場合は、{minutes} 分後に最善の判断で続行します。）','notify.summary.clarificationNoBody':'「{title}」の実行に確認が必要です：\n{questions}\n（issue を開いて回答してください。回答がない場合は、{minutes} 分後に最善の判断で続行します。）','notify.summary.seeConversation':'（詳しくは会話を確認してください。）',
  },
  ko: {
    'notify.summary.statusTransition':'{title}: {from} → {to}','notify.summary.issueBlocked':'{title}: {detail}','notify.summary.planReview':'계획 확인 대기 중: {title}','notify.summary.autoGitFailure':'{title}: 자동 {action}에 실패했습니다(완료에는 영향 없음): {detail}','notify.summary.mergeReview':'변경 사항 검토 대기 중: {title}','notify.summary.conversationDisplaced':'{title}: 프로젝트에서 다른 대화를 사용 중이어서 실행을 일시 중지했습니다. 이 issue로 돌아오면 자동으로 재개됩니다.','notify.summary.menuStuck':'CLI 프롬프트가 {minutes}분 동안 대기 중입니다. 입력이 필요합니다: {context}','notify.summary.rateLimited':'{title}: 사용량 한도에 도달했습니다. {minutes}분 후 자동으로 재개됩니다.','notify.summary.clarification':'“{title}” 실행 중 확인이 필요합니다:\n요구 사항: {body}\n{questions}\n(issue를 열어 답변해 주세요. 답변이 없으면 {minutes}분 후 최선의 판단으로 계속합니다.)','notify.summary.clarificationNoBody':'“{title}” 실행 중 확인이 필요합니다:\n{questions}\n(issue를 열어 답변해 주세요. 답변이 없으면 {minutes}분 후 최선의 판단으로 계속합니다.)','notify.summary.seeConversation':'(자세한 내용은 대화를 확인하세요.)',
  },
  es: {
    'notify.summary.statusTransition':'{title}: {from} → {to}','notify.summary.issueBlocked':'{title}: {detail}','notify.summary.planReview':'Plan pendiente de confirmación: {title}','notify.summary.autoGitFailure':'{title}: falló la operación {action} automática (la finalización no se ve afectada): {detail}','notify.summary.mergeReview':'Cambios pendientes de revisión: {title}','notify.summary.conversationDisplaced':'{title}: la ejecución se ha pausado porque hay otra conversación activa en el proyecto. Vuelve a este issue para reanudarla automáticamente.','notify.summary.menuStuck':'La solicitud de la CLI lleva {minutes} minutos esperando y necesita tu intervención: {context}','notify.summary.rateLimited':'{title}: se alcanzó el límite de uso; la ejecución se reanudará automáticamente en {minutes} minutos.','notify.summary.clarification':'“{title}” necesita una aclaración durante la ejecución:\nRequisito: {body}\n{questions}\n(Abre el issue para responder. Si no respondes, la ejecución continuará con el mejor criterio en {minutes} minutos.)','notify.summary.clarificationNoBody':'“{title}” necesita una aclaración durante la ejecución:\n{questions}\n(Abre el issue para responder. Si no respondes, la ejecución continuará con el mejor criterio en {minutes} minutos.)','notify.summary.seeConversation':'(Consulta la conversación para obtener más detalles.)',
  },
  fr: {
    'notify.summary.statusTransition':'{title} : {from} → {to}','notify.summary.issueBlocked':'{title} : {detail}','notify.summary.planReview':'Plan en attente de confirmation : {title}','notify.summary.autoGitFailure':'{title} : échec de l’opération {action} automatique (sans incidence sur la finalisation) : {detail}','notify.summary.mergeReview':'Modifications en attente de validation : {title}','notify.summary.conversationDisplaced':'{title} : l’exécution est suspendue, car une autre conversation du projet est active. Revenez à cet issue pour reprendre automatiquement.','notify.summary.menuStuck':'L’invite de la CLI attend depuis {minutes} minutes et nécessite votre intervention : {context}','notify.summary.rateLimited':'{title} : limite d’utilisation atteinte ; l’exécution reprendra automatiquement dans {minutes} minutes.','notify.summary.clarification':'« {title} » nécessite une précision pendant l’exécution :\nExigence : {body}\n{questions}\n(Ouvrez l’issue pour répondre. Sans réponse, l’exécution continuera au mieux dans {minutes} minutes.)','notify.summary.clarificationNoBody':'« {title} » nécessite une précision pendant l’exécution :\n{questions}\n(Ouvrez l’issue pour répondre. Sans réponse, l’exécution continuera au mieux dans {minutes} minutes.)','notify.summary.seeConversation':'(Consultez la conversation pour plus de détails.)',
  },
  de: {
    'notify.summary.statusTransition':'{title}: {from} → {to}','notify.summary.issueBlocked':'{title}: {detail}','notify.summary.planReview':'Plan wartet auf Bestätigung: {title}','notify.summary.autoGitFailure':'{title}: automatisches {action} fehlgeschlagen (der Abschluss ist nicht betroffen): {detail}','notify.summary.mergeReview':'Änderungen warten auf Prüfung: {title}','notify.summary.conversationDisplaced':'{title}: Die Ausführung wurde pausiert, weil eine andere Projektunterhaltung aktiv ist. Kehren Sie zu diesem Issue zurück, um automatisch fortzufahren.','notify.summary.menuStuck':'Die CLI-Eingabeaufforderung wartet seit {minutes} Minuten und benötigt Ihre Eingabe: {context}','notify.summary.rateLimited':'{title}: Nutzungslimit erreicht; die Ausführung wird in {minutes} Minuten automatisch fortgesetzt.','notify.summary.clarification':'„{title}“ muss während der Ausführung geklärt werden:\nAnforderung: {body}\n{questions}\n(Öffnen Sie das Issue, um zu antworten. Ohne Antwort wird die Ausführung in {minutes} Minuten nach bestem Ermessen fortgesetzt.)','notify.summary.clarificationNoBody':'„{title}“ muss während der Ausführung geklärt werden:\n{questions}\n(Öffnen Sie das Issue, um zu antworten. Ohne Antwort wird die Ausführung in {minutes} Minuten nach bestem Ermessen fortgesetzt.)','notify.summary.seeConversation':'(Weitere Einzelheiten finden Sie in der Unterhaltung.)',
  },
  'pt-BR': {
    'notify.summary.statusTransition':'{title}: {from} → {to}','notify.summary.issueBlocked':'{title}: {detail}','notify.summary.planReview':'Plano aguardando confirmação: {title}','notify.summary.autoGitFailure':'{title}: falha no {action} automático (a conclusão não foi afetada): {detail}','notify.summary.mergeReview':'Alterações aguardando revisão: {title}','notify.summary.conversationDisplaced':'{title}: a execução foi pausada porque outra conversa do projeto está ativa. Volte para este issue para retomar automaticamente.','notify.summary.menuStuck':'O prompt da CLI está aguardando há {minutes} minutos e precisa da sua intervenção: {context}','notify.summary.rateLimited':'{title}: limite de uso atingido; a execução será retomada automaticamente em {minutes} minutos.','notify.summary.clarification':'“{title}” precisa de esclarecimento durante a execução:\nRequisito: {body}\n{questions}\n(Abra o issue para responder. Sem resposta, a execução continuará com o melhor julgamento em {minutes} minutos.)','notify.summary.clarificationNoBody':'“{title}” precisa de esclarecimento durante a execução:\n{questions}\n(Abra o issue para responder. Sem resposta, a execução continuará com o melhor julgamento em {minutes} minutos.)','notify.summary.seeConversation':'(Consulte a conversa para ver os detalhes.)',
  },
  ru: {
    'notify.summary.statusTransition':'{title}: {from} → {to}','notify.summary.issueBlocked':'{title}: {detail}','notify.summary.planReview':'План ожидает подтверждения: {title}','notify.summary.autoGitFailure':'{title}: не удалось автоматически выполнить {action} (это не влияет на завершение): {detail}','notify.summary.mergeReview':'Изменения ожидают проверки: {title}','notify.summary.conversationDisplaced':'{title}: выполнение приостановлено, так как активен другой диалог проекта. Вернитесь к этой задаче, чтобы продолжить автоматически.','notify.summary.menuStuck':'Запрос CLI ожидает уже {minutes} мин. и требует вашего ввода: {context}','notify.summary.rateLimited':'{title}: достигнут лимит использования; выполнение автоматически продолжится через {minutes} мин.','notify.summary.clarification':'Во время выполнения «{title}» требуется уточнение:\nТребование: {body}\n{questions}\n(Откройте задачу, чтобы ответить. Без ответа выполнение продолжится наилучшим образом через {minutes} мин.)','notify.summary.clarificationNoBody':'Во время выполнения «{title}» требуется уточнение:\n{questions}\n(Откройте задачу, чтобы ответить. Без ответа выполнение продолжится наилучшим образом через {minutes} мин.)','notify.summary.seeConversation':'(Подробности см. в диалоге.)',
  },
};

const additionalSummaryTranslations: Record<Exclude<SupportedLocale, 'en'>, Partial<Messages>> = {
  'zh-Hans': { 'notify.summary.moduleOrganization':'模块整理分析已完成：共 {total} 项建议（合并 {merges} / 改名 {renames} / 新建模块 {creates} / 移动 issue {moves}）。\n请在项目页的“模块”面板中逐项审查。','notify.summary.analysisClarification':'“{title}”分析后需要确认：\n需求：{body}\n{questions}\n（可以不回复；回复内容会并入需求。）','notify.summary.analysisClarificationNoBody':'“{title}”分析后需要确认：\n{questions}\n（可以不回复；回复内容会并入需求。）' },
  'zh-Hant': { 'notify.summary.moduleOrganization':'模組整理分析已完成：共 {total} 項建議（合併 {merges} / 改名 {renames} / 新增模組 {creates} / 移動 issue {moves}）。\n請在專案頁的「模組」面板中逐項審查。','notify.summary.analysisClarification':'「{title}」分析後需要確認：\n需求：{body}\n{questions}\n（可以不回覆；回覆內容會併入需求。）','notify.summary.analysisClarificationNoBody':'「{title}」分析後需要確認：\n{questions}\n（可以不回覆；回覆內容會併入需求。）' },
  ja: { 'notify.summary.moduleOrganization':'モジュール整理の分析が完了しました：提案 {total} 件（統合 {merges} / 名前変更 {renames} / 新規モジュール {creates} / issue の移動 {moves}）。\nプロジェクトページの「モジュール」パネルで各操作を確認してください。','notify.summary.analysisClarification':'「{title}」の分析後に確認が必要です：\n要件：{body}\n{questions}\n（返信は任意です。返信内容は要件に追加されます。）','notify.summary.analysisClarificationNoBody':'「{title}」の分析後に確認が必要です：\n{questions}\n（返信は任意です。返信内容は要件に追加されます。）' },
  ko: { 'notify.summary.moduleOrganization':'모듈 구성 분석이 완료되었습니다. 제안 {total}개(병합 {merges} / 이름 변경 {renames} / 새 모듈 {creates} / issue 이동 {moves}).\n프로젝트 페이지의 모듈 패널에서 각 작업을 검토하세요.','notify.summary.analysisClarification':'“{title}” 분석 후 확인이 필요합니다:\n요구 사항: {body}\n{questions}\n(답변은 선택 사항이며, 답변 내용은 요구 사항에 추가됩니다.)','notify.summary.analysisClarificationNoBody':'“{title}” 분석 후 확인이 필요합니다:\n{questions}\n(답변은 선택 사항이며, 답변 내용은 요구 사항에 추가됩니다.)' },
  es: { 'notify.summary.moduleOrganization':'El análisis de organización de módulos ha finalizado: {total} sugerencias ({merges} fusiones / {renames} cambios de nombre / {creates} módulos nuevos / {moves} traslados de issues).\nAbre el panel Módulos de la página del proyecto para revisar cada acción.','notify.summary.analysisClarification':'“{title}” necesita una aclaración tras el análisis:\nRequisito: {body}\n{questions}\n(La respuesta es opcional; cualquier respuesta se añadirá al requisito.)','notify.summary.analysisClarificationNoBody':'“{title}” necesita una aclaración tras el análisis:\n{questions}\n(La respuesta es opcional; cualquier respuesta se añadirá al requisito.)' },
  fr: { 'notify.summary.moduleOrganization':'L’analyse de l’organisation des modules est terminée : {total} suggestions ({merges} fusions / {renames} renommages / {creates} nouveaux modules / {moves} déplacements d’issues).\nOuvrez le panneau Modules de la page du projet pour examiner chaque action.','notify.summary.analysisClarification':'« {title} » nécessite une précision après analyse :\nExigence : {body}\n{questions}\n(La réponse est facultative ; toute réponse sera ajoutée à l’exigence.)','notify.summary.analysisClarificationNoBody':'« {title} » nécessite une précision après analyse :\n{questions}\n(La réponse est facultative ; toute réponse sera ajoutée à l’exigence.)' },
  de: { 'notify.summary.moduleOrganization':'Die Analyse der Modulorganisation ist abgeschlossen: {total} Vorschläge ({merges} Zusammenführungen / {renames} Umbenennungen / {creates} neue Module / {moves} Issue-Verschiebungen).\nPrüfen Sie jede Aktion im Bereich „Module“ auf der Projektseite.','notify.summary.analysisClarification':'„{title}“ muss nach der Analyse geklärt werden:\nAnforderung: {body}\n{questions}\n(Eine Antwort ist optional; sie wird der Anforderung hinzugefügt.)','notify.summary.analysisClarificationNoBody':'„{title}“ muss nach der Analyse geklärt werden:\n{questions}\n(Eine Antwort ist optional; sie wird der Anforderung hinzugefügt.)' },
  'pt-BR': { 'notify.summary.moduleOrganization':'A análise da organização dos módulos foi concluída: {total} sugestões ({merges} mesclagens / {renames} renomeações / {creates} novos módulos / {moves} movimentações de issues).\nAbra o painel Módulos na página do projeto para revisar cada ação.','notify.summary.analysisClarification':'“{title}” precisa de esclarecimento após a análise:\nRequisito: {body}\n{questions}\n(A resposta é opcional; qualquer resposta será adicionada ao requisito.)','notify.summary.analysisClarificationNoBody':'“{title}” precisa de esclarecimento após a análise:\n{questions}\n(A resposta é opcional; qualquer resposta será adicionada ao requisito.)' },
  ru: { 'notify.summary.moduleOrganization':'Анализ структуры модулей завершён: предложений — {total} (объединений — {merges} / переименований — {renames} / новых модулей — {creates} / переносов задач — {moves}).\nОткройте раздел «Модули» на странице проекта и проверьте каждое действие.','notify.summary.analysisClarification':'После анализа «{title}» требуется уточнение:\nТребование: {body}\n{questions}\n(Ответ необязателен; любой ответ будет добавлен к требованию.)','notify.summary.analysisClarificationNoBody':'После анализа «{title}» требуется уточнение:\n{questions}\n(Ответ необязателен; любой ответ будет добавлен к требованию.)' },
};

const deliverySummaryTranslations: Record<Exclude<SupportedLocale, 'en'>, Partial<Messages>> = {
  'zh-Hans': { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline}（等待你回复）','notify.summary.approvalSelection':'🔢 需要你选择：{context}（请打开网页继续。）' },
  'zh-Hant': { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline}（等待你的回覆）','notify.summary.approvalSelection':'🔢 需要你選擇：{context}（請開啟網頁繼續。）' },
  ja: { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline}（返信待ち）','notify.summary.approvalSelection':'🔢 選択が必要です：{context}（Webアプリを開いて続行してください。）' },
  ko: { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline}(답변 대기 중)','notify.summary.approvalSelection':'🔢 선택이 필요합니다: {context}(웹 앱을 열어 계속하세요.)' },
  es: { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline} (Esperando tu respuesta)','notify.summary.approvalSelection':'🔢 Se requiere una selección: {context} (Abre la aplicación web para continuar.)' },
  fr: { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline} (En attente de votre réponse)','notify.summary.approvalSelection':'🔢 Sélection requise : {context} (Ouvrez l’application web pour continuer.)' },
  de: { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline} (Warten auf Ihre Antwort)','notify.summary.approvalSelection':'🔢 Auswahl erforderlich: {context} (Öffnen Sie die Web-App, um fortzufahren.)' },
  'pt-BR': { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline} (Aguardando sua resposta)','notify.summary.approvalSelection':'🔢 É necessário fazer uma escolha: {context} (Abra o aplicativo web para continuar.)' },
  ru: { 'notify.summary.progress':'{emoji} {headline}','notify.summary.progressNeedsReply':'{emoji} {headline} (Ожидается ваш ответ)','notify.summary.approvalSelection':'🔢 Требуется выбор: {context} (Откройте веб-приложение, чтобы продолжить.)' },
};

/** #273：自动重试到顶转人工。issue 不 block，文案统一强调「仍在运行」。 */
const attentionTranslations: Record<Exclude<SupportedLocale, 'en'>, Partial<Messages>> = {
  'zh-Hans': { 'notify.choiceWaiting':'🔢 [issue #{id}] 等你选择：{summary}',
    'notify.summary.clarifySuccessLow':'{project}：创建时澄清基本都在失败（最近 {total} 次只成功 {ok} 次）。每次白跑都照付一次通读代码库的钱——去看看 clarify 的 error 事件。',
    'notify.summary.regressionFailed':'{project}：定时全量回归在「{label}」失败（退出码：{code}）。没有建 issue，也没有任何任务被阻塞——有空看一眼。',
    'notify.summary.stopLossPaused':'{title}：已被止损闸暂停（{reason, select, blocked {累计受阻 {blocks} 次} stage_reentry {同阶段重入 {reentries} 次} other {累计运行 {hours} 小时}}）。没有失败，也没有取消——确认后可从停下的那个阶段继续。',
    'notify.summary.autoRetryExhausted':'{title}：{reason, select, nudge {自动催办} judge {完成判定} other {自动重试}}连续 {count} 次没有进展，已停止。issue 仍在运行、未被阻塞，请抽空看一眼。' },
  'zh-Hant': { 'notify.choiceWaiting':'🔢 [issue #{id}] 等你選擇：{summary}',
    'notify.summary.clarifySuccessLow':'{project}：建立時釐清幾乎都在失敗（最近 {total} 次只成功 {ok} 次）。每次白跑都照付一次通讀程式碼的錢——去看看 clarify 的 error 事件。',
    'notify.summary.regressionFailed':'{project}：定時全量迴歸在「{label}」失敗（結束代碼：{code}）。沒有建立 issue，也沒有任何任務被阻擋——有空看一下。',
    'notify.summary.stopLossPaused':'{title}：已被停損閘暫停（{reason, select, blocked {累計受阻 {blocks} 次} stage_reentry {同階段重入 {reentries} 次} other {累計執行 {hours} 小時}}）。沒有失敗，也沒有取消——確認後可從停下的那個階段繼續。',
    'notify.summary.autoRetryExhausted':'{title}：{reason, select, nudge {自動催辦} judge {完成判定} other {自動重試}}連續 {count} 次沒有進展，已停止。issue 仍在執行、未被阻擋，請抽空看一眼。' },
  ja: { 'notify.choiceWaiting':'🔢 [issue #{id}] 選択が必要です：{summary}',
    'notify.summary.clarifySuccessLow':'{project}：作成時の確認分析がほぼ失敗しています（直近 {total} 回中 {ok} 回のみ成功）。失敗しても毎回コードベース全体の読み取り分は課金されます。clarify の error イベントを確認してください。',
    'notify.summary.regressionFailed':'{project}：定期の全量リグレッションが「{label}」で失敗しました（終了コード: {code}）。issue は作成しておらず、停止したタスクもありません。時間のあるときに確認してください。',
    'notify.summary.stopLossPaused':'{title}：コスト上限により一時停止しました（{reason, select, blocked {ブロック回数 {blocks}} stage_reentry {同一段階への再突入 {reentries} 回} other {累計実行 {hours} 時間}}）。失敗でもキャンセルでもありません。確認すれば停止した段階から再開できます。',
    'notify.summary.autoRetryExhausted':'{title}：{reason, select, nudge {自動リマインド} judge {完了判定} other {自動リトライ}}が {count} 回続けて進展せず、停止しました。issue は実行中でブロックされていません。確認してください。' },
  ko: { 'notify.choiceWaiting':'🔢 [issue #{id}] 선택이 필요합니다: {summary}',
    'notify.summary.clarifySuccessLow':'{project}: 생성 시 확인 분석이 대부분 실패하고 있습니다(최근 {total}회 중 {ok}회 성공). 실패해도 저장소 전체를 읽는 비용은 그대로 나갑니다. clarify error 이벤트를 확인하세요.',
    'notify.summary.regressionFailed':'{project}: 정기 전체 회귀 테스트가 「{label}」에서 실패했습니다(종료 코드: {code}). issue를 만들지 않았고 중단된 작업도 없습니다. 시간 될 때 확인해 주세요.',
    'notify.summary.stopLossPaused':'{title}: 비용 상한으로 일시 중지되었습니다({reason, select, blocked {차단 횟수 {blocks}} stage_reentry {같은 단계 재진입 {reentries}회} other {누적 실행 {hours}시간}}). 실패도 취소도 아니며, 확인하면 멈춘 단계부터 계속할 수 있습니다.',
    'notify.summary.autoRetryExhausted':'{title}: {reason, select, nudge {자동 알림} judge {완료 판정} other {자동 재시도}}이(가) {count}회 연속 진전 없이 중단되었습니다. issue는 계속 실행 중이며 차단되지 않았습니다. 한번 확인해 주세요.' },
  es: { 'notify.choiceWaiting':'🔢 [issue #{id}] Necesita tu elección: {summary}',
    'notify.summary.clarifySuccessLow':'{project}: el análisis de aclaración al crear falla casi siempre ({ok} de {total} con éxito). Cada intento fallido paga igual una lectura completa del repositorio; revisa los eventos de error de clarify.',
    'notify.summary.regressionFailed':'{project}: la regresión completa programada falló en «{label}» (código de salida: {code}). No se creó ninguna issue ni se bloqueó nada; revísalo cuando puedas.',
    'notify.summary.stopLossPaused':'{title}: pausada por el límite de gasto ({reason, select, blocked {bloqueos: {blocks}} stage_reentry {reingresos a la etapa: {reentries}} other {tiempo de ejecución: {hours} h}}). No ha fallado ni se ha cancelado; confirma para continuar desde la etapa en la que se detuvo.',
    'notify.summary.autoRetryExhausted':'{title}: {reason, select, nudge {los recordatorios automáticos} judge {las comprobaciones de finalización} other {los reintentos automáticos}} se detuvieron tras {count, plural, one {# intento} other {# intentos}} sin avance. La issue sigue en ejecución y no está bloqueada; échale un vistazo.' },
  fr: { 'notify.choiceWaiting':'🔢 [issue #{id}] Votre choix est requis : {summary}',
    'notify.summary.clarifySuccessLow':'{project} : l’analyse de clarification à la création échoue presque toujours ({ok} succès sur {total}). Chaque échec paie quand même une lecture complète du dépôt — regardez les événements d’erreur clarify.',
    'notify.summary.regressionFailed':'{project} : la régression complète planifiée a échoué sur « {label} » (code de sortie : {code}). Aucune issue n’a été créée et rien n’est bloqué ; jetez-y un œil quand vous pourrez.',
    'notify.summary.stopLossPaused':'{title} : mise en pause par le garde-fou de coût ({reason, select, blocked {blocages : {blocks}} stage_reentry {retours à l’étape : {reentries}} other {temps d’exécution : {hours} h}}). Rien n’a échoué et rien n’a été annulé ; confirmez pour reprendre à l’étape où elle s’est arrêtée.',
    'notify.summary.autoRetryExhausted':'{title} : {reason, select, nudge {les relances automatiques} judge {les vérifications de fin} other {les nouvelles tentatives automatiques}} se sont arrêtées après {count, plural, one {# tentative} other {# tentatives}} sans progrès. L’issue est toujours en cours et n’est pas bloquée ; jetez-y un œil.' },
  de: { 'notify.choiceWaiting':'🔢 [issue #{id}] Ihre Auswahl wird benötigt: {summary}',
    'notify.summary.clarifySuccessLow':'{project}: Die Klärungsanalyse beim Anlegen schlägt fast immer fehl ({ok} von {total} zuletzt erfolgreich). Jeder Fehlversuch bezahlt trotzdem einen vollständigen Repository-Durchlauf – sieh dir die clarify-Fehlerereignisse an.',
    'notify.summary.regressionFailed':'{project}: Die geplante vollständige Regression ist bei „{label}“ fehlgeschlagen (Exit-Code: {code}). Es wurde kein Issue angelegt und nichts blockiert – schau es dir bei Gelegenheit an.',
    'notify.summary.stopLossPaused':'{title}: durch die Kostenbremse pausiert ({reason, select, blocked {Blockierungen: {blocks}} stage_reentry {Wiedereintritte in die Phase: {reentries}} other {Laufzeit: {hours} h}}). Nichts ist fehlgeschlagen und nichts wurde abgebrochen – bestätigen Sie, um bei der angehaltenen Phase fortzufahren.',
    'notify.summary.autoRetryExhausted':'{title}: {reason, select, nudge {Automatische Erinnerungen} judge {Abschlussprüfungen} other {Automatische Wiederholungen}} wurden nach {count, plural, one {# Versuch} other {# Versuchen}} ohne Fortschritt gestoppt. Das Issue läuft weiter und ist nicht blockiert – bitte einmal nachsehen.' },
  'pt-BR': { 'notify.choiceWaiting':'🔢 [issue #{id}] Precisa da sua escolha: {summary}',
    'notify.summary.clarifySuccessLow':'{project}: a análise de esclarecimento na criação está quase sempre falhando ({ok} de {total} com sucesso). Cada tentativa falha paga do mesmo jeito uma leitura completa do repositório — veja os eventos de erro do clarify.',
    'notify.summary.regressionFailed':'{project}: a regressão completa agendada falhou em “{label}” (código de saída: {code}). Nenhuma issue foi criada e nada está bloqueado — dê uma olhada quando puder.',
    'notify.summary.stopLossPaused':'{title}: pausada pelo limite de custo ({reason, select, blocked {bloqueios: {blocks}} stage_reentry {reentradas na etapa: {reentries}} other {tempo de execução: {hours} h}}). Nada falhou e nada foi cancelado; confirme para continuar da etapa em que parou.',
    'notify.summary.autoRetryExhausted':'{title}: {reason, select, nudge {os lembretes automáticos} judge {as verificações de conclusão} other {as novas tentativas automáticas}} pararam após {count, plural, one {# tentativa} other {# tentativas}} sem avanço. A issue continua em execução e não foi bloqueada; dê uma olhada.' },
  ru: { 'notify.choiceWaiting':'🔢 [issue #{id}] Нужен ваш выбор: {summary}',
    'notify.summary.clarifySuccessLow':'{project}: анализ уточнений при создании почти всегда падает (успешны {ok} из {total} последних). Каждый неудачный запуск всё равно оплачивает полное чтение репозитория — посмотрите события ошибок clarify.',
    'notify.summary.regressionFailed':'{project}: плановая полная регрессия упала на «{label}» (код выхода: {code}). Задача не создавалась и ничего не заблокировано — посмотрите, когда будет время.',
    'notify.summary.stopLossPaused':'{title}: приостановлено ограничителем расходов ({reason, select, blocked {блокировок: {blocks}} stage_reentry {повторных входов в этап: {reentries}} other {время работы: {hours} ч}}). Ничего не сломалось и не отменено — подтвердите, чтобы продолжить с того этапа, где остановились.',
    'notify.summary.autoRetryExhausted':'{title}: {reason, select, nudge {автоматические напоминания} judge {проверки завершения} other {автоматические повторы}} остановлены после {count, plural, one {# попытки} few {# попыток} many {# попыток} other {# попытки}} без прогресса. Issue всё ещё выполняется и не заблокирована — загляните, пожалуйста.' },
};

export const notifyMessages = {
  en,
  'zh-Hans': locale({ ...summaryTranslations['zh-Hans'], ...additionalSummaryTranslations['zh-Hans'], ...deliverySummaryTranslations['zh-Hans'], 'notify.statusChange':'🔄 [issue #{id}] {summary}','notify.done':'✅ [issue #{id}] 完成：{summary}','notify.blocked':'⛔ [issue #{id}] 受阻：{summary}','notify.notExplained':'未说明','notify.gateWaiting':'卡点待确认','notify.waitingReply':'💬 **它在等你回话** — 请直接回复或到网页处理','notify.selectionTitle':'🔢 {title} 需要你选择','notify.planEmpty':'（计划为空，请到网页查看详情）','notify.planMore':'…（共 {count} 步，其余见网页）','notify.planHeading':'**计划（{count} 步 · {mode}）**','notify.modeTeam':'团队（一次性交付）','notify.modeSeq':'顺序执行','notify.branch':'分支','notify.diffFailed':'⚠️ diff 生成出错：{error}','notify.diffTruncated':'（diff 超长已截断）','notify.fullDiffWeb':'完整 diff 请到网页 review。','notify.planGateTitle':'🚦 计划待确认 · issue #{id}','notify.mergeGateTitle':'🔍 合并前 review · issue #{id}','notify.approve':'✅ 批准','notify.reject':'❌ 拒绝','notify.oneTimeFooter':'按钮一次性有效；拒绝的详细意见请到网页补充。','notify.bindTest':'✅ PandaDOS 绑定验证：收到本消息表示通知可以送达。','notify.rejectNote':'飞书卡片一键拒绝；详细意见请到网页补充。','notify.invalidCard':'无效的卡片回调','notify.cardExpired':'卡片已失效','notify.cardHandled':'这张卡已处理过','notify.cardNotYours':'这张卡不是发给你的','notify.gateUnavailable':'卡点处理未接线，请到网页操作','notify.failed':'处理失败','notify.approved':'✅ 已批准','notify.rejected':'❌ 已拒绝；详细意见请到网页补充','notify.invalidSelection':'无效的选择回调','notify.selectedOption':'已选择第 {index} 项', ...attentionTranslations['zh-Hans'] }),
  'zh-Hant': locale({ ...summaryTranslations['zh-Hant'], ...additionalSummaryTranslations['zh-Hant'], ...deliverySummaryTranslations['zh-Hant'], 'notify.statusChange':'🔄 [issue #{id}] {summary}','notify.done':'✅ [issue #{id}] 完成：{summary}','notify.blocked':'⛔ [issue #{id}] 受阻：{summary}','notify.notExplained':'未說明','notify.gateWaiting':'檢查點待確認','notify.waitingReply':'💬 **正在等你回覆** — 請直接回覆或到網頁處理','notify.selectionTitle':'🔢 {title} 需要你選擇','notify.planGateTitle':'🚦 計畫待確認 · issue #{id}','notify.mergeGateTitle':'🔍 合併前審查 · issue #{id}','notify.approve':'✅ 核准','notify.reject':'❌ 拒絕','notify.bindTest':'✅ PandaDOS 連線測試：收到此訊息表示通知可以送達。', ...attentionTranslations['zh-Hant'] }),
  ja: locale({ ...summaryTranslations.ja, ...additionalSummaryTranslations.ja, ...deliverySummaryTranslations.ja, 'notify.statusChange':'🔄 [issue #{id}] {summary}','notify.done':'✅ [issue #{id}] 完了：{summary}','notify.blocked':'⛔ [issue #{id}] ブロック中：{summary}','notify.notExplained':'説明なし','notify.gateWaiting':'確認待ち','notify.waitingReply':'💬 **返信を待っています** — ここで返信するかWebアプリで対応してください','notify.selectionTitle':'🔢 {title} で選択が必要です','notify.planEmpty':'（計画が空です。詳細はWebアプリで確認してください。）','notify.planMore':'…（全{count}ステップ。残りはWebアプリで確認）','notify.planHeading':'**計画（{count}ステップ · {mode}）**','notify.modeTeam':'チーム（一括納品）','notify.modeSeq':'順次実行','notify.branch':'ブランチ','notify.diffFailed':'⚠️ diffを生成できませんでした：{error}','notify.diffTruncated':'（diffは長いため省略されました）','notify.fullDiffWeb':'完全なdiffはWebアプリで確認してください。','notify.planGateTitle':'🚦 計画の確認待ち · issue #{id}','notify.mergeGateTitle':'🔍 マージ前レビュー · issue #{id}','notify.approve':'✅ 承認','notify.reject':'❌ 却下','notify.oneTimeFooter':'ボタンは一度だけ有効です。却下の詳しい理由はWebアプリで入力してください。','notify.bindTest':'✅ PandaDOS 接続テスト：このメッセージが届けば通知を受信できます。','notify.rejectNote':'Feishuカードから却下しました。詳しい理由はWebアプリで入力してください。','notify.invalidCard':'無効なカードコールバックです','notify.cardExpired':'このカードは期限切れです','notify.cardHandled':'このカードは処理済みです','notify.cardNotYours':'このカードはあなた宛てではありません','notify.gateUnavailable':'Webアプリで操作してください','notify.failed':'処理できませんでした','notify.approved':'✅ 承認しました','notify.rejected':'❌ 却下しました。詳しい理由はWebアプリで入力してください','notify.invalidSelection':'無効な選択コールバックです','notify.selectedOption':'{index}番目の項目を選択しました', ...attentionTranslations.ja }),
  ko: locale({ ...summaryTranslations.ko, ...additionalSummaryTranslations.ko, ...deliverySummaryTranslations.ko, 'notify.done':'✅ [issue #{id}] 완료: {summary}','notify.blocked':'⛔ [issue #{id}] 차단됨: {summary}','notify.gateWaiting':'확인 대기 중','notify.approve':'✅ 승인','notify.reject':'❌ 거부','notify.bindTest':'✅ PandaDOS 연결 테스트: 이 메시지가 도착하면 알림을 받을 수 있습니다.', ...attentionTranslations.ko }),
  es: locale({ ...summaryTranslations.es, ...additionalSummaryTranslations.es, ...deliverySummaryTranslations.es, 'notify.done':'✅ [issue #{id}] Completada: {summary}','notify.blocked':'⛔ [issue #{id}] Bloqueada: {summary}','notify.gateWaiting':'Confirmación pendiente','notify.approve':'✅ Aprobar','notify.reject':'❌ Rechazar','notify.bindTest':'✅ Prueba de conexión de PandaDOS: este mensaje confirma que puedes recibir notificaciones.', ...attentionTranslations.es }),
  fr: locale({ ...summaryTranslations.fr, ...additionalSummaryTranslations.fr, ...deliverySummaryTranslations.fr, 'notify.done':'✅ [issue #{id}] Terminée : {summary}','notify.blocked':'⛔ [issue #{id}] Bloquée : {summary}','notify.gateWaiting':'Confirmation requise','notify.approve':'✅ Approuver','notify.reject':'❌ Refuser','notify.bindTest':'✅ Test de connexion PandaDOS : ce message confirme que vous pouvez recevoir les notifications.', ...attentionTranslations.fr }),
  de: locale({ ...summaryTranslations.de, ...additionalSummaryTranslations.de, ...deliverySummaryTranslations.de, 'notify.done':'✅ [issue #{id}] Erledigt: {summary}','notify.blocked':'⛔ [issue #{id}] Blockiert: {summary}','notify.gateWaiting':'Bestätigung ausstehend','notify.approve':'✅ Genehmigen','notify.reject':'❌ Ablehnen','notify.bindTest':'✅ PandaDOS-Verbindungstest: Diese Nachricht bestätigt, dass Benachrichtigungen Sie erreichen.', ...attentionTranslations.de }),
  'pt-BR': locale({ ...summaryTranslations['pt-BR'], ...additionalSummaryTranslations['pt-BR'], ...deliverySummaryTranslations['pt-BR'], 'notify.done':'✅ [issue #{id}] Concluída: {summary}','notify.blocked':'⛔ [issue #{id}] Bloqueada: {summary}','notify.gateWaiting':'Aguardando confirmação','notify.approve':'✅ Aprovar','notify.reject':'❌ Rejeitar','notify.bindTest':'✅ Teste de conexão do PandaDOS: esta mensagem confirma que você pode receber notificações.', ...attentionTranslations['pt-BR'] }),
  ru: locale({ ...summaryTranslations.ru, ...additionalSummaryTranslations.ru, ...deliverySummaryTranslations.ru, 'notify.done':'✅ [issue #{id}] Выполнено: {summary}','notify.blocked':'⛔ [issue #{id}] Заблокировано: {summary}','notify.gateWaiting':'Ожидает подтверждения','notify.approve':'✅ Одобрить','notify.reject':'❌ Отклонить','notify.bindTest':'✅ Проверка подключения PandaDOS: это сообщение подтверждает доставку уведомлений.', ...attentionTranslations.ru }),
} as const satisfies Record<SupportedLocale, Messages>;
