const en = {
  'status.pending':'To do','status.clarifying':'Clarifying','status.planning':'Planning','status.planReview':'Plan review',
  'status.implementing':'Implementing','status.testing':'Testing','status.mergeReview':'Merge review','status.merging':'Merging',
  'status.done':'Done','status.blocked':'Blocked','status.cancelled':'Cancelled','status.awaitingClarify':'Waiting for your answer',
  'status.awaitingClarifyHint':'The agent is waiting for clarification. Open the issue and answer in the clarification panel.',
  'status.waitingChoice':'Waiting for your choice','status.waitingChoiceHint':'An agent prompt needs your choice. Open the run view or use the Feishu card.',
  'status.categoryTask':'Task','status.categoryDesign':'Design','status.categoryDebug':'Debug','status.modelInUse':'Model in use: {model}',
  'status.online':'Online','status.offline':'Offline','status.unknown':'Unknown',
} as const;
type Shape = { [K in keyof typeof en]: string };
const l = (v: Partial<Record<keyof Shape,string>>): Shape => ({...en,...v});
export const statusMessages = {
  en,
  'zh-Hans': l({'status.pending':'待办','status.clarifying':'澄清中','status.planning':'规划中','status.planReview':'计划待确认','status.implementing':'实现中','status.testing':'测试中','status.mergeReview':'合并待确认','status.merging':'合并中','status.done':'完成','status.blocked':'受阻','status.cancelled':'已取消','status.awaitingClarify':'等待你澄清','status.awaitingClarifyHint':'执行代理正在等待你回答澄清问题。请打开 issue，在顶部澄清面板中回答。','status.waitingChoice':'等你选择','status.waitingChoiceHint':'代理弹窗正在等待你的选择。请打开执行页或使用飞书卡片。','status.categoryTask':'任务','status.categoryDesign':'设计','status.categoryDebug':'调试','status.modelInUse':'当前使用的模型：{model}','status.online':'在线','status.offline':'离线','status.unknown':'未知'}),
  'zh-Hant': l({'status.pending':'待辦','status.clarifying':'釐清中','status.planning':'規劃中','status.planReview':'計畫待確認','status.implementing':'實作中','status.testing':'測試中','status.mergeReview':'合併待確認','status.merging':'合併中','status.done':'完成','status.blocked':'受阻','status.cancelled':'已取消','status.awaitingClarify':'等待你釐清','status.awaitingClarifyHint':'執行代理正在等待你的說明。請開啟 issue，在釐清面板中回答。','status.waitingChoice':'等待你的選擇','status.waitingChoiceHint':'代理提示正在等待你的選擇。請開啟執行頁或使用飛書卡片。','status.categoryTask':'工作','status.categoryDesign':'設計','status.categoryDebug':'除錯','status.modelInUse':'目前使用的模型：{model}','status.online':'線上','status.offline':'離線','status.unknown':'未知'}),
  ja: l({'status.pending':'To do','status.clarifying':'確認中','status.planning':'計画中','status.planReview':'計画レビュー','status.implementing':'実装中','status.testing':'テスト中','status.mergeReview':'マージレビュー','status.merging':'マージ中','status.done':'完了','status.blocked':'ブロック中','status.cancelled':'キャンセル済み','status.awaitingClarify':'回答待ち','status.awaitingClarifyHint':'エージェントが確認事項への回答を待っています。issueを開いて回答してください。','status.waitingChoice':'選択待ち','status.waitingChoiceHint':'エージェントのプロンプトが選択を待っています。実行画面またはFeishuカードから回答してください。','status.categoryTask':'タスク','status.categoryDesign':'設計','status.categoryDebug':'デバッグ','status.modelInUse':'使用中のモデル：{model}','status.online':'オンライン','status.offline':'オフライン','status.unknown':'不明'}),
  ko: l({'status.pending':'할 일','status.clarifying':'확인 중','status.planning':'계획 중','status.planReview':'계획 검토','status.implementing':'구현 중','status.testing':'테스트 중','status.mergeReview':'병합 검토','status.merging':'병합 중','status.done':'완료','status.blocked':'차단됨','status.cancelled':'취소됨','status.awaitingClarify':'답변 대기','status.awaitingClarifyHint':'에이전트가 확인 답변을 기다립니다. issue를 열고 답변하세요.','status.waitingChoice':'선택 대기','status.waitingChoiceHint':'에이전트 프롬프트가 선택을 기다립니다. 실행 화면이나 Feishu 카드에서 응답하세요.','status.categoryTask':'작업','status.categoryDesign':'설계','status.categoryDebug':'디버그','status.modelInUse':'사용 중인 모델: {model}','status.online':'온라인','status.offline':'오프라인','status.unknown':'알 수 없음'}),
  es: l({'status.pending':'Pendiente','status.clarifying':'Aclarando','status.planning':'Planificando','status.planReview':'Revisión del plan','status.implementing':'Implementando','status.testing':'Probando','status.mergeReview':'Revisión de fusión','status.merging':'Fusionando','status.done':'Completada','status.blocked':'Bloqueada','status.cancelled':'Cancelada','status.awaitingClarify':'Esperando tu respuesta','status.awaitingClarifyHint':'El agente espera una aclaración. Abre la issue y responde en el panel.','status.waitingChoice':'Esperando tu elección','status.waitingChoiceHint':'Un aviso del agente requiere tu elección. Abre la ejecución o usa la tarjeta de Feishu.','status.categoryTask':'Tarea','status.categoryDesign':'Diseño','status.categoryDebug':'Depuración','status.modelInUse':'Modelo en uso: {model}','status.online':'En línea','status.offline':'Sin conexión','status.unknown':'Desconocido'}),
  fr: l({'status.pending':'À faire','status.clarifying':'Clarification','status.planning':'Planification','status.planReview':'Révision du plan','status.implementing':'Implémentation','status.testing':'Tests','status.mergeReview':'Révision de fusion','status.merging':'Fusion','status.done':'Terminée','status.blocked':'Bloquée','status.cancelled':'Annulée','status.awaitingClarify':'En attente de votre réponse','status.awaitingClarifyHint':'L’agent attend une clarification. Ouvrez l’issue et répondez dans le panneau.','status.waitingChoice':'En attente de votre choix','status.waitingChoiceHint':'Une invite de l’agent attend votre choix. Ouvrez l’exécution ou utilisez la carte Feishu.','status.categoryTask':'Tâche','status.categoryDesign':'Conception','status.categoryDebug':'Débogage','status.modelInUse':'Modèle utilisé : {model}','status.online':'En ligne','status.offline':'Hors ligne','status.unknown':'Inconnu'}),
  de: l({'status.pending':'Zu erledigen','status.clarifying':'Klärung','status.planning':'Planung','status.planReview':'Planprüfung','status.implementing':'Implementierung','status.testing':'Test','status.mergeReview':'Merge-Prüfung','status.merging':'Zusammenführung','status.done':'Erledigt','status.blocked':'Blockiert','status.cancelled':'Abgebrochen','status.awaitingClarify':'Wartet auf Ihre Antwort','status.awaitingClarifyHint':'Der Agent wartet auf eine Klärung. Öffnen Sie das Issue und antworten Sie im Klärungsbereich.','status.waitingChoice':'Wartet auf Ihre Auswahl','status.waitingChoiceHint':'Eine Agentenabfrage benötigt Ihre Auswahl. Öffnen Sie die Ausführung oder die Feishu-Karte.','status.categoryTask':'Aufgabe','status.categoryDesign':'Design','status.categoryDebug':'Debugging','status.modelInUse':'Verwendetes Modell: {model}','status.online':'Online','status.offline':'Offline','status.unknown':'Unbekannt'}),
  'pt-BR': l({'status.pending':'A fazer','status.clarifying':'Esclarecendo','status.planning':'Planejando','status.planReview':'Revisão do plano','status.implementing':'Implementando','status.testing':'Testando','status.mergeReview':'Revisão de mesclagem','status.merging':'Mesclando','status.done':'Concluída','status.blocked':'Bloqueada','status.cancelled':'Cancelada','status.awaitingClarify':'Aguardando sua resposta','status.awaitingClarifyHint':'O agente aguarda um esclarecimento. Abra a issue e responda no painel.','status.waitingChoice':'Aguardando sua escolha','status.waitingChoiceHint':'Um aviso do agente precisa da sua escolha. Abra a execução ou use o cartão do Feishu.','status.categoryTask':'Tarefa','status.categoryDesign':'Design','status.categoryDebug':'Depuração','status.modelInUse':'Modelo em uso: {model}','status.online':'Online','status.offline':'Offline','status.unknown':'Desconhecido'}),
  ru: l({'status.pending':'К выполнению','status.clarifying':'Уточнение','status.planning':'Планирование','status.planReview':'Проверка плана','status.implementing':'Реализация','status.testing':'Тестирование','status.mergeReview':'Проверка слияния','status.merging':'Слияние','status.done':'Готово','status.blocked':'Заблокировано','status.cancelled':'Отменено','status.awaitingClarify':'Ждёт вашего ответа','status.awaitingClarifyHint':'Агент ждёт уточнения. Откройте issue и ответьте в панели уточнения.','status.waitingChoice':'Ждёт вашего выбора','status.waitingChoiceHint':'Запрос агента ждёт вашего выбора. Откройте выполнение или карточку Feishu.','status.categoryTask':'Задача','status.categoryDesign':'Проектирование','status.categoryDebug':'Отладка','status.modelInUse':'Используемая модель: {model}','status.online':'В сети','status.offline':'Не в сети','status.unknown':'Неизвестно'}),
} as const;
